apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::210026634594:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-M0UGM7EVNWBA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::210026634594:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-27T10:03:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1751"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: eea857ae-e011-4339-8c06-49fd5e08c851
